# Builder stage: install deps and build the Next app
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --legacy-peer-deps
COPY . .
RUN npm run build

# Runner stage: copy standalone output and run
FROM node:18-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production PORT=3000

# copy standalone app generated by Next
COPY --from=builder /app/.next/standalone ./
# copy static files and public
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

# install only production deps from the standalone package.json
RUN npm ci --production --ignore-scripts --no-audit --no-fund

EXPOSE 3000
CMD ["node", "server.js"]